/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminInnerNav: typeof import('./src/components/AdminInnerNav.vue')['default']
    AdminPagination: typeof import('./src/components/AdminPagination.vue')['default']
    AvatarCropper: typeof import('./src/components/AvatarCropper.vue')['default']
    BingoIssueGrid: typeof import('./src/components/BingoIssueGrid.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GlobalBackground: typeof import('./src/components/GlobalBackground.vue')['default']
    MaimaiRing: typeof import('./src/components/effects/MaimaiRing.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NeonActionButton: typeof import('./src/components/NeonActionButton.vue')['default']
    NeonCard: typeof import('./src/components/NeonCard.vue')['default']
    NeonDateTimePicker: typeof import('./src/components/NeonDateTimePicker.vue')['default']
    NeonInput: typeof import('./src/components/NeonInput.vue')['default']
    NeonRankTable: typeof import('./src/components/NeonRankTable.vue')['default']
    PentagonPuzzleStar: typeof import('./src/components/PentagonPuzzleStar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreImageUploader: typeof import('./src/components/ScoreImageUploader.vue')['default']
    TaskScoreAction: typeof import('./src/components/TaskScoreAction.vue')['default']
  }
}
