location /images/ {
    alias /var/webserver/images/;
}
location /scores/ {
    alias /var/webserver/scores/;
}
location /avatars/ {
    alias /var/webserver/avatars/;
}
location /files/ {
    alias /var/webserver/files/;
}
location /banners/ {
    alias /var/webserver/banners/;
}