server {
    listen 80;  # 监听 80 端口

    server_name localhost;

    client_max_body_size 5M;

    location /api/ {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    location / {
        # 指向你的前端服务地址
        root /var/www/CDMGA-vue/current_main;
        index index.html;
        try_files $uri $uri/ /index.html;

    }
    include /etc/nginx/snippets/cdmga_assets.conf;

    # 您可以添加访问日志和错误日志的路径
    access_log /var/log/nginx/cdmga.access.log;
    error_log /var/log/nginx/cdmga.error.log;
}
# =========================================================
# DEV 环境
# =========================================================
server {
    listen 80;
    server_name dev.localhost;

    client_max_body_size 5M;

    access_log /var/log/nginx/cdmga_dev.access.log;
    error_log  /var/log/nginx/cdmga_dev.error.log;

    location /api/ {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/CDMGA-vue/current_dev;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    include /etc/nginx/snippets/cdmga_assets.conf;
}