name: CD-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  update_npm:
    uses: ./.github/workflows/pnpm_update.yml
    with:
      channel: dev
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_SUDO: ${{ secrets.SSH_SUDO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}