name: mvn-update
on:
  workflow_call:
    secrets:
      SSH_HOST: {}
      SSH_SUDO: {}
      SSH_PRIVATE_KEY: {}
      SSH_PORT: {}
  workflow_dispatch:

jobs:
  mvn-build:
    # if: |
    #   github.event_name == 'workflow_dispatch' ||
    #   github.event_name == 'push' 
    name: mvn build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: webpage
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean package -P prod
      
    - name: List JAR file
      run: ls -la target/*.jar

    - name: Create backup timestamp
      id: backup-time
      run: echo "date=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Deploy JAR to server via SCP
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_SUDO }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "webpage/target/*.jar"
        target: "/opt/webserver/upload/"
        strip_components: 2

    - name: Deploy and restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_SUDO }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          # 停止服务
          sudo systemctl stop webserver.service

          # 备份旧版本
          if [ -f "/opt/webserver/app/webpage-0.0.1-SNAPSHOT.jar" ]; then
              sudo mv /opt/webserver/app/webpage-0.0.1-SNAPSHOT.jar "/opt/webserver/backup/webpage_${{ steps.backup-time.outputs.date }}.jar"
          fi

          # 清理7天前的备份
          find /opt/webserver/backup/ -name "webpage_*.jar" -mtime +7 -exec sudo rm -f {} \; || true
          echo "Old backups cleaned."

          # 移动新版本
          sudo mv /opt/webserver/upload/webpage-0.0.1-SNAPSHOT.jar /opt/webserver/app/

          # 权限调整
          sudo chown webserver:webserver /opt/webserver/app/webpage-0.0.1-SNAPSHOT.jar
          sudo chmod 750 /opt/webserver/app/webpage-0.0.1-SNAPSHOT.jar

          # 启动服务
          sudo systemctl start webserver.service

          # 检查服务
          sleep 5
          sudo systemctl status webserver.service --no-pager

          echo "等待应用启动..."
          success=0
          for i in {1..10}; do
            if sudo lsof -t -i:8080 > /dev/null 2>&1; then
              echo "应用启动成功!"
              success=1
              break
            else
              echo "第 $i 次检测，服务未启动，5秒后重试..."
              sleep 5
            fi
          done
          if [ "$success" -ne 1 ]; then
            echo "警告: 应用连续10次检测未正常启动，请检查日志"
            sudo journalctl -u webserver.service -n 50 --no-pager
            exit 1
          fi
